packages:
  - packages/*
  - apps/*

allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  workerd: false

minimumReleaseAgeExclude:
  - astro@7.3.1

updateConfig:
  ignoreDependencies:
    - typescript
