name: Publish to npm

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Bump package version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Bumping @mizuchilabs/lyvo to $VERSION"
          pnpm --filter @mizuchilabs/lyvo exec npm version $VERSION --no-git-tag-version

      - name: Build package
        run: pnpm --filter @mizuchilabs/lyvo build

      - name: Publish to npm
        run: pnpm --filter @mizuchilabs/lyvo publish
