name: Test

on:
  push:
    branches: [main]
    paths:
      - "**/*.js"
      - "**/*.ts"
      - "**/*.astro"
  pull_request:
    branches: [main]
    paths:
      - "**/*.js"
      - "**/*.ts"
      - "**/*.astro"
      - "**/package.json"
      - "**/pnpm-lock.yaml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: "lts/*"

      - uses: pnpm/action-setup@v6

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint and Build
        run: |
          pnpm lint
          pnpm build
